env:
  node: true
  jest: true
  es6: true
extends: 
  - 'eslint:recommended'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
    - allowTemplateLiterals: true
  semi:
    - warn
    - always
  no-console: 0
  no-unused-vars: 0
